- name: Install SAP HANA
  hosts: hana
  become: yes

  roles:
              - mk-ansible-roles.subscribe-rhn
              - linux-system-roles.timesync
              - mk-ansible-roles.disk-init
              - mk-ansible-roles.saphana-preconfigure
              - mk-ansible-roles.saphana-deploy
