---
- name: Install SAP HANA
  hosts: hana
  become: yes

  # variables are all defined in group_vars/hana and host_vars
  # so run this playbook with
  # ansible-playbook -l hana1.example.com -vv install-hana.yml

  roles:
          - mk-ansible-roles.subscribe-rhn
          - linux-system-roles.timesync
          - mk-ansible-roles.disk-init
          - mk-ansible-roles.saphana-preconfigure
          - mk-ansible-roles.saphana-deploy

