---
# NOTE: This playbook has two plays, because we need the handler to run after the hostagent is installed

- name: Install SAP HANA Hostagent
  hosts: all

  roles:
    - sap-hana-hostagent

- name: Install SAP HANA
  hosts: all

  roles:
    - sap-hana-deployment
    # sap-hana-hsr


